name: CI

on:
  push:
    branches:
      - 'main'
      - 'develop'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Fonts
        run: fc-list

#      - name: Build
#        run: make build
